### ISSUE TITLE
Memory Error when making calls to Adafruit IO

### ISSUE THREAD

**Issue by c-seymour-UEC** [UlnoowegEducationCenter/GrowEnclosure#1]
Memory error occurs irregularly when making updating the Adafruit IO sensor feeds:

  Traceback (most recent call last):
    File "code.py", line 308, in <module>
    File "asyncio/core.py", line 297, in run
    File "asyncio/core.py", line 261, in run_until_complete
    File "asyncio/core.py", line 246, in run_until_complete
    File "code.py", line 302, in main
    File "asyncio/funcs.py", line 113, in gather
    File "asyncio/funcs.py", line 108, in gather
    File "asyncio/core.py", line 246, in run_until_complete
    File "code.py", line 188, in updateSensorData
    File "adafruit_io/adafruit_io.py", line 611, in send_data
    File "adafruit_io/adafruit_io.py", line 551, in _post
    File "adafruit_requests.py", line 715, in post
    File "adafruit_requests.py", line 650, in request
    File "adafruit_requests.py", line 510, in _get_socket
  MemoryError:

**Comment by c-seymour-UEC** [comment]
If theres no way to reduce the memory usage of the adafruit io calls than we will have to reduce the overall memory usage of the system. Some places to start might be:
- Replacing the asyncio based structure with a simpler main loop that checks time and makes function calls appropriately (basically a complete re-write)
- reducing the amounts of imports with 'from X import Y' statements instead of just 'import X'
- compiling any remaining '.py' files in the library to '.mpy's

**Comment by TNarakol-UEC** [comment]
No longer valid, hardware switched to Pi 3A+.
